### ISSUE TITLE
How do you set 'includeTransactions'?

### ISSUE THREAD

**Issue by sjordan1975** [AuthorizeNet/sample-code-php#102]
The [AuthorizeNet documentation](https://developer.authorize.net/api/reference/index.html#recurring-billing-get-subscription) references being able to set includeTransactions property:

````
[BOOLEAN] Indicates whether to include information about transactions for this subscription.

If set to true, information about the most recent 20 transactions for this subscription will be included in the response.
````

How is this done with the SDK? 

Similar to [#280](https://github.com/AuthorizeNet/sdk-php/issues/280)

Thank you

**Comment by enterlight** [comment]
Could somebody paste the required code to get the recent transactions from the Get Subscription SDK call?

**Comment by enterlight** [comment]
@sjordan1975  I fiddled and fiddled and ended up making a php curl call using json just for that specific request.  I will look at your forked project.  Thanks for your help

**Comment by sjordan1975** [comment]
I suspect that includeTransactions support has been implemented in the underlying Authorize.net API; however, the PHP SDK is woefully out of date. And no sample code has been forthcoming from Authorize.net (earliest request is from June 2016)

So, for my purposes, I forked the PHP SDK:
https://github.com/sjordan1975/sdk-php

I implemented get ARB Transaction from Get Subscription sufficient for what I needed.

Specifically, I modified the following 4 files:
lib/net/authorize/api/contract/v1/ARBGetSubscriptionRequest.php
lib/net/authorize/api/contract/v1/ARBSubscriptionMaskedType.php
lib/net/authorize/api/yml/v1/ARBGetSubscriptionRequest.yml
lib/net/authorize/api/yml/v1/ARBSubscriptionMaskedType.yml

Note: I have used TransactionDetailsType whereas I suspect the actual type should be something like ARBTransactionType, but the yaml definition is missing and I have not defined it

The result is for now is not all transaction data is populated; HOWEVER, transId IS populated and this is good enough to make an additional API call to get Transaction Details.

Feel free to have at it. Code provided AS IS to the Community. YMMV

**Comment by brianmc** [comment]
This is coming soon in the SDKs and we'll make sure to include it in sample code as well.  We're trying to keep not more than a month behind API updates but the latest release has been a little delayed.

**Comment by ashtru** [comment]
_includeTransactions_ has been added to the ARBGetSubscription request as part of the [latest release](https://github.com/AuthorizeNet/sdk-php/releases)!
Kindly change your composer.json to use version 1.9.5 of authorizenet/authorizenet similar to the [sample code composer](https://github.com/AuthorizeNet/sample-code-php/blob/master/composer.json).

**Comment by sjordan1975** [comment]
@ashtru Thank you. I'll check it out.

It would also be nice to update the [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/get-subscription.php) to demonstrate how to use this function.

**Comment by ashtru** [comment]
Thanks @sjordan1975  . The [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/get-subscription.php#L) is updated.

Happy Coding!
Authorize.Net

**Comment by sjordan1975** [comment]
Hi @ashtru I see you updated the [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/get-subscription.php) to set `setIncludeTransactions`  to _true_

I think it would be helpful to update the section of code which displays results...

**Example**

Current code snippet:
````if($response->getMessages()->getResultCode() == "Ok")
{
    // Success
    echo "SUCCESS: GetSubscription:" . "\n";
    // Displaying the details
    echo "Subscription Name: " . $response->getSubscription()->getName(). "\n";
    echo "Subscription amount: " . $response->getSubscription()->getAmount(). "\n";
    echo "Subscription status: " . $response->getSubscription()->getStatus(). "\n";
    echo "Subscription Description: " . $response->getSubscription()->getProfile()->getDescription(). "\n";
    echo "Customer Profile ID: " .  $response->getSubscription()->getProfile()->getCustomerProfileId() . "\n";
    echo "Customer payment Profile ID: ". $response->getSubscription()->getProfile()->getPaymentProfile()->getCustomerPaymentProfileId() . "\n";
}
````

I suggest something like the follow (see comments inline):
````if($response->getMessages()->getResultCode() == "Ok")
{
    // Success
    echo "SUCCESS: GetSubscription:" . "\n";
    // Displaying the details
    echo "Subscription Name: " . $response->getSubscription()->getName(). "\n";
    echo "Subscription amount: " . $response->getSubscription()->getAmount(). "\n";
    echo "Subscription status: " . $response->getSubscription()->getStatus(). "\n";
    echo "Subscription Description: " . $response->getSubscription()->getProfile()->getDescription(). "\n";
    echo "Customer Profile ID: " .  $response->getSubscription()->getProfile()->getCustomerProfileId() . "\n";
    echo "Customer payment Profile ID: ". $response->getSubscription()->getProfile()->getPaymentProfile()->getCustomerPaymentProfileId() . "\n";

    echo "Previous transactions: " . "\n";
    // INSERT EXAMPLE LOOP OVER TRANSACTIONS RETURNED FROM CALL TO ARBGetSubscriptionRequest
}
````

The goal is to help future devs as much as possible; you want to make it easy for people to use and _want to use_ the SDK (IMHO)

**Comment by ashtru** [comment]
Thanks for the suggestion, @sjordan1975 . The [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/get-subscription.php) is updated.

Happy Coding!
Authorize.Net
