### ISSUE TITLE
How Create A Invoice with PHP API

### ISSUE THREAD

**Issue by lucasdevsquad** [AuthorizeNet/sample-code-php#111]
Hello, how I create a invoice (like this https://www.authorize.net/solutions/merchantsolutions/merchantservices/invoicing/) with API in PHP?.
Thanks,

**Comment by anuragg29** [comment]
Hi @lucasdevsquad 

We are actively developing REST APIs  with native JSON support.
 If you are interested in being a beta tester of our REST APIs, please email developer_feedback@authorize.net 

You should be able to use the invoicing REST  APIs in it for managing invoicing  . 

Thanks
Anurag
