### ISSUE TITLE
Error on line 63

### ISSUE THREAD

**Issue by SilkySully** [AuthorizeNet/sample-code-php#114]
This Code (CustomerProfiles->create-customer-payment-profile.php) won't run correctly as there is a typo on line 63.  it reads paymentprofile when it should be paymentProfile.

**Comment by adavidw** [comment]
Line #63 is referring to the variable that's set earlier (which is called `paymentprofile`), so not a typo.

**Comment by SilkySully** [comment]
Ah, got me...  I have been looking at so much other code that uses paymentProfile this one is an anomaly.  I was copy and pasting into my code is how I got the error.  (It was about 3-4 am when I posted this, lol).  Thanks for the heads-up.
