### ISSUE TITLE
No Longer working

### ISSUE THREAD

**Issue by ameshkin** [AuthorizeNet/sample-code-php#118]
Has this been deprecated?  This is what I am being told.

**Comment by ashtru** [comment]
Hi @ameshkin, thanks for you query.
If you are referring to the sample-code-php repository, it has not been deprecated. There is no plan in sight to deprecate it.

Can you please provide the source of what led you to this anticipation?

**Comment by chsriniv9** [comment]
Issue seems to be query on the sample-code-php. As @ashtru has answered the query, closing this issue. Feel free to re-open if further assistance is needed on sample-code-php
