### ISSUE TITLE
AuthorizeNet supports only credit card payments ?

### ISSUE THREAD

**Issue by sastri448** [AuthorizeNet/sample-code-php#119]
Hi ,

Based on  the git read me file i downloaded run the folder using composer instructions.

**\sample-code-php-master\PaymentTransactions** 
Above folder contains different payments. I observe that all are related to credit payment ? even though function names also representing the credit card payment example:   

**authorizeCreditCard
chargeCreditCard**

**Comment by ashtru** [comment]
Hi @sastri448 
**Can you elaborate on the different modes of payments you are expecting, other than credit cards?**

Authorize.Net is a payment gateway and it supports payments via:
- All major credit and debit cards such as Visa, MasterCard, American Express, Discover, Diner's Club, JCB, and so on, both online and retail.
- [ECheck](https://www.authorize.net/payments/echeck/), also called ACH payments. [[Sample code for echeck](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/debit-bank-account.php)]

Additionally,  it supports integrations for merchants using other digital payment solutions including Paypal, Visa Checkout and Apple Pay.

In case, you are new to the payments domain, you can go through [How Payments Work](https://www.authorize.net/resources/how-payments-work/)  for a start.

**Comment by chsriniv9** [comment]
Based on the inputs and solution provided by @ashtru closing this issue. Feel free to re-open in case further assistance required.
