### ISSUE TITLE
getArbTransactions() is not returning any transactions

### ISSUE THREAD

**Issue by safrick** [AuthorizeNet/sample-code-php#125]
Using the sample-code-php/RecurringBilling/get-subscription.php

This line of code always returns an empty array.
$transactions = $response->getSubscription()->getArbTransactions();

Note that the other details of the subscription are being returned and I've verified that there are transactions under 2 different ARB ID's, both in the sandbox and production.

**Comment by ashtru** [comment]
1. Are you passing the _includeTransactions_ as _true_ in the request, similar to [line 25](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/get-subscription.php#L25) of the sample code?

2.   a. How old are the subscriptions? 
  b. What is the **status of the transactions** in the [sandbox](sandbox.authorize.net)/[production](account.authorize.net)?

3. Can you share the contents of your `phplog` file which will have the full xml response from the API. You can find it in the same folder as your PHP SDK.

4. Can you also share the code snippet for traversing the _arbTransactions_ array?

**Comment by safrick** [comment]
#1 was what I missed. 
Thank you very much for your help.
