### ISSUE TITLE
No Option for setting Request Headers as JSON

### ISSUE THREAD

**Issue by buttflattery** [AuthorizeNet/sample-code-php#140]
in the `getTransactionDetails()` example for php you have provided, there isnt any example to set the response type to `json` instead of `xml`, as i need to save the response json string in my databases for the transaction logs and wanted to mimic the same response that is shown by the [**API Live Console**](https://developer.authorize.net/api/reference/#transaction-reporting-get-transaction-details) , but i cant find any way to do so using the php-sdk.

**Comment by kikmak42** [comment]
Hi @buttflattery,

The intent of the SDKs are to provide language libraries which helps easy integration with the AuthorizeNet API. Thus the underlying SDK can be using xml or json requests for communication to the server which user need not worry about.

Right now the PHP SDK uses XML but luckily for PHP we have been working on a new version of the SDK on JSON, it currently in public ALPHA and undergoing testing, you can have look into that if that fulfills your requirement 

For 2.0.0-ALPHA SDK
[Github Release Link](https://github.com/AuthorizeNet/sdk-php/releases/tag/2.0.0-ALPHA)
[Packagist Link](https://packagist.org/packages/authorizenet/authorizenet#2.0.0-ALPHA)

Thanks
Kaushik

**Comment by buttflattery** [comment]
Hmm, that is what I thought but wanted to ask about to the concerned person, thanks for the reply I will wait for the stable build to be released for the production server otherwise it would be waste of time as I cant use the Alpha Build on the production server. Thanks for your time @kikmak42
