### ISSUE TITLE
Charge customer profile - returning customer (and saved card)

### ISSUE THREAD

**Issue by peppeocchi** [AuthorizeNet/sample-code-php#23]
The sample code [here](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php) covers only a scenario when a customer profile and a customer payment profile are created.

What if I already have a customer profile id and a customer payment profile id?
How should I use the `TransactionRequestType `?

From those ids I'm retrieving the customer profile and the customer profile id (when retrieving that data an instance of `*MaskedType ` is returned that is useless [here](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php#L142)), how can I set a customerProfileId and a customerPaymentProfileId in that object?

**Comment by brianmc** [comment]
Hi @peppeocchi, you're absolutely right, that sample was not even demonstrating the correct concept.  I've updated it to simply charge a payment profile : https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php 

Thanks so much for the feedback,

Brian
