### ISSUE TITLE
missing CustomerPaymentProfileSortingType Class

### ISSUE THREAD

**Issue by jonjonus** [AuthorizeNet/sample-code-php#32]
Hi

I downloaded the master branch. When I try to run
sample-code-php/CustomerProfiles/get-customer-payment-profile-list.php
It cant find the **CustomerPaymentProfileSortingType** Class and I don't see it on the code. Am I doing something wrong?

Thanks!

**Comment by ashtru** [comment]
Waht is the exact error you are getting? Are you using composer?

**Comment by ashtru** [comment]
It seems it was related to the syntax error highlighted and fixed in #30. It has been merged now, thanks to @*hackur*.

**Comment by brianmc** [comment]
Thanks for the feedback
