### ISSUE TITLE
How do I get the payment profile ID out of ARBGetSubscriptionRequest?

### ISSUE THREAD

**Issue by safrick** [AuthorizeNet/sample-code-php#34]
How do I get the payment profile ID out of ARBGetSubscriptionRequest using the PHP SDK?

It's not shown in the sample listed at https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/get-subscription.php

**Comment by ashtru** [comment]
echo "Customer payment Profile ID: ". $response->getSubscription()->getProfile()->getPaymentProfile()->getCustomerPaymentProfileId() . "\n";

[ARBGetSubscriptionResponse] (https://github.com/AuthorizeNet/sdk-php/blob/01990f02cf8f0350370ae6e606342041b4ed5586/lib/net/authorize/api/contract/v1/ARBGetSubscriptionResponse.php)
has subscription of type [ARBSubscriptionMaskedType](https://github.com/AuthorizeNet/sdk-php/blob/01990f02cf8f0350370ae6e606342041b4ed5586/lib/net/authorize/api/contract/v1/ARBSubscriptionMaskedType.php)
which has profile of type [SubscriptionCustomerProfileType](https://github.com/AuthorizeNet/sdk-php/blob/01990f02cf8f0350370ae6e606342041b4ed5586/lib/net/authorize/api/contract/v1/SubscriptionCustomerProfileType.php)
which has getPaymentProfile() of type [CustomerPaymentProfileMaskedType](https://github.com/AuthorizeNet/sdk-php/blob/01990f02cf8f0350370ae6e606342041b4ed5586/lib/net/authorize/api/contract/v1/CustomerPaymentProfileMaskedType.php)
which has getCustomerPaymentProfileId()
