### ISSUE TITLE
error on foreach if no unsettled transactions

### ISSUE THREAD

**Issue by CTerrell** [AuthorizeNet/sample-code-php#39]
php sample code errors out if no unsettled transactions.  if statement prior to foreach should read:

if (($response->getTransactions() != null) && ($response->getMessages()->getResultCode() == "Ok"))

**Comment by ashtru** [comment]
@CTerrell  Thanks for pointing this out. We will make this update.

**Comment by adavidw** [comment]
Since there hasn't been an update, I'm going to close this issue. If you have more information to provide related to this issue, feel free to reopen it.
