### ISSUE TITLE
Got PHP error

### ISSUE THREAD

**Issue by musaddiq-pk** [AuthorizeNet/sample-code-php#42]
Hello,
I got the following php error while running [authoriz.net\sample-code-php-master\PaymentTransactions/refund-transaction.php]([authoriz.netsample-code-php-masterPaymentTransactions/refund-transaction.php) code.

Warning: require(C:\xampp\htdocs/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\croppic-master\refund-transaction.php on line 2

**Comment by ashtru** [comment]
Please try running composer. Give the location of` php.ini `when asked for php path.
On running composer, it generates the `vendor `folder which has `autoload.php`.
In the require, make sure you are giving the correct location of `autoload.php `generated.

**Comment by daniel-farina** [comment]
You should really use a virtual machine, windows will give you a lot of headaches. I recommend using: 

https://scotch.io/bar-talk/announcing-scotch-box-2-5

**Comment by ashtru** [comment]
Thanks for raising the issue @musaddiq-pk . I am going to close this issue, please reopen it if you have further problems or questions.

**Comment by adavidw** [comment]
In the absence of any further questions, I'll close this issue for now. Please let us know if you need any more information or help.
