### ISSUE TITLE
Get fatal error

### ISSUE THREAD

**Issue by LawanyaD** [AuthorizeNet/sample-code-php#49]
When I run refund-transaction.php. I got an following error

**Fatal error: Class 'Symfony\Component\Yaml\Yaml' not found in /opt/lampp/htdocs/payment/vendor/jms/serializer/src/JMS/Serializer/Metadata/Driver/YamlDriver.php on line 35**

Please hands to me

**Comment by ashtru** [comment]
Are you still getting the issue? There was a new release 1.9.1 of the sdk. I am hoping that should fix it.

**Comment by adavidw** [comment]
In the absence of any further questions, I'll close this issue for now. Please let us know if you need any more information or help.
