### ISSUE TITLE
same error across samples - phplog file unwritable

### ISSUE THREAD

**Issue by netpassprod1** [AuthorizeNet/sample-code-php#53]
Warning: file_put_contents(phplog): failed to open stream: Permission denied in /var/www/vhosts/mydomain.com/httpdocs/library/anetsdk/lib/net/authorize/util/Log.php on line 269

I have the define("AUTHORIZENET_LOG_FILE","phplog"); line ahead of the 'use' statements for including the namespaces for authorize.net for contract and controller.

I still get the error outputting lots of times ahead of the executeWithApiResposne() function call.

WHERE do I assign the phplog value so this function has something to use rather than generating warnings?

**Comment by ashtru** [comment]
Do not define the constant ("AUTHORIZENET_LOG_FILE","phplog"), if you do not want to see the logs.
Otherwise, if you want the logs, try changing the permissions of the root folder (sample-code-php) .

**Comment by ashtru** [comment]
@netpassprod1 were you able to fix this issue?
I am closing this issue for now. If you have any questions, feel free to reopen this issue.

**Comment by adavidw** [comment]
In the absence of any further questions, I'll close this issue for now. Please let us know if you need any more information or help.
