### ISSUE TITLE
Unexplained Error

### ISSUE THREAD

**Issue by GregCatalano** [AuthorizeNet/sample-code-php#55]
When I call createCustomerProfileFromTransaction($transactionId) I get E00059 The authentication type is not allowed for this method call. Does anyone know the cause of this? I'm sending to the SANDBOX server.

**Comment by brianmc** [comment]
If you do a getTransactionDetails on the same transId, what is the transaction type & status?

**Comment by GregCatalano** [comment]
Thanks for the response. It gave me the same thing and I realized I had the password wrong. Now I'm on to a new error... Progress :+1:
