### ISSUE TITLE
How to get Customer Payment Profile Id?

### ISSUE THREAD

**Issue by GregCatalano** [AuthorizeNet/sample-code-php#56]
After createCustomerProfileFromTransaction is there an easy way to determine which CustomerPaymentProfileId was just used/set? 

It's easy to $response->getCustomerProfileId() and I see a getCustomerPaymentProfileIdList() method, but not sure if I have to loop through that and compare with transaction data just transmitted or if there's a better way.

**Comment by brianmc** [comment]
There's always just one element in the CustomerPaymentProfileIdList that's the payment profile that was just created from the transaction.

**Comment by GregCatalano** [comment]
got it, thanks! array w/ 1 element.
