### ISSUE TITLE
Unable to pass parameter in AuthorizeNet Sample Code for PHP

### ISSUE THREAD

**Issue by techauth** [AuthorizeNet/sample-code-php#60]
I am using following code for making transaction with my sandbox account which is working fine. But I am unable to pass following parameters :-

1) Customer Name 
2) Customer Phone number 
3) Customer Email address 
4) Order Id 
5) Order Description

Code URL  :  https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/authorize-credit-card.php

**Comment by ashtru** [comment]
If you see the [api reference](http://developer.authorize.net/api/reference/) for `Charge a credit card`, the xml request fields include:-

- billTo/shipTo
- - phoneNumber
- - firstName
- - lastName
- customer
- - email
- order
- - invoiceNumber
- - description

**Comment by techauth** [comment]
Hi,

Thanks for the response as mentioned I am using following code for "Auth and Capture" mode

https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/authorize-credit-card.php

But for some strange reason I am still unable to make a successful transaction. The problem is when a customer fill their and press submit button it shows "Transaction successful". But when I go to "Reports" to capture specific transaction in my authorizenet account. It declines all the transactions showing one of the reasons below:

 
1) Declined  (Authorization with the card issuer was successful but the transaction was declined due to an address or ZIP code mismatch with the address on file with the card issuing bank based on the settings in the Merchant Interface.)

2) Declined  (Card declined by issuer - Contact card issuer to determine reason.)

My question is if the above exception can happen then why it shows "Transaction Successful" message in my application? Or Is there any other code to implement Authorzinet for Auth and Capture mode with PHP application ?

**Comment by ashtru** [comment]
1. Sorry for the confusion, but for a successful transaction, the [response code](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/authorize-credit-card.php#L46) returned must be 1. Refer the responseCode field in Response tab for [authorize a credit card](http://developer.authorize.net/api/reference/#payment-transactions-authorize-a-credit-card) api.
![image](https://cloud.githubusercontent.com/assets/14973353/21339229/7532e264-c6a3-11e6-811b-9ed3a70c9a93.png)
2. You need to review your settings in MINT (Merchant Interface), and check which fraud filters have been applied, and adjust them accordingly. It seems to be one of the address based filters. Refer the [documentation](https://www.authorize.net/solutions/merchantsolutions/merchantservices/frauddetectionsuite/).

[Here](https://support.authorize.net/authkb/index?page=content&id=A521&actp=LIST) is another discussion, describing the actions that can be chosen, when one of the filters is triggered.

**Comment by ashtru** [comment]
Please reply if you were able to fix this issue. Meanwhile, this will issues be closed. Feel free to reopen in case of further queries.
