### ISSUE TITLE
createCustomerProfileTransaction sample code request

### ISSUE THREAD

**Issue by rmckeel** [AuthorizeNet/sample-code-php#61]
Thank you for your hard work on this sample PHP code library!

There is a function `createCustomerProfileTransaction` used in the [SDK-PHP test suite](https://github.com/AuthorizeNet/sdk-php/blob/master/tests/AuthorizeNetCIM_Test.php#L415).  However, I am not seeing the function `createCustomerProfileTransaction` used anywhere in this [sample-code-php library](https://github.com/AuthorizeNet/sample-code-php).

Would you be able to add a sample that included this function?

Thank you for considering,

  Ryan

**Comment by rmckeel** [comment]
I noticed [this sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php), but I don't know the library well enough to know if that is the same as a transaction like `AnetAPI\CreateCustomerProfileTransactionRequest`.

**Comment by ashtru** [comment]
If you have a customer profile, it is okay to charge the customer profile using the [charge customer profile sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php#L24).

The only important thing is to make sure a valid payment profile id is assigned, as seen on [line 18](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php#L18).

The [SDK PHP Suite example](https://github.com/AuthorizeNet/sdk-php/blob/master/tests/AuthorizeNetCIM_Test.php#L415) you saw is an older method of requesting from the SDK, but is deprecated now.
You won't see the shipping address field, as in the [old code](https://github.com/AuthorizeNet/sdk-php/blob/master/tests/AuthorizeNetCIM_Test.php#L393) in charge-customer-profile sample.

**Comment by ashtru** [comment]
I looked at the [CustomerProfilePaymentType](https://github.com/AuthorizeNet/sdk-php/blob/9d24edc675362b6349983205b8288d178fa0c469/lib/net/authorize/api/contract/v1/CustomerProfilePaymentType.php#L116) class.
So, for setting the shipping profile in the charge customer profile sample code, you would need to add a line like this:
 ` $profileToCharge->setShippingProfileId($shippingProfileId);`

Feel free to reach out in case of queries.

**Comment by rmckeel** [comment]
@ashtru Thanks for your review of this.  Good to know about the deprecated code, glad my 'hunch' was correct in using the sample code and not the test code.  Hope the tests can be updated to reflect (and prevent others from being confused).

Thanks for your hard work on this library!  I will close this out now.

**Comment by brianmc** [comment]
Hi Ryan,

That's a deprecated method, you can now use the standard createTransaction to charge a profile: http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile

Brian
