### ISSUE TITLE
Error: Failed opening required 'vendor/autoload.php'

### ISSUE THREAD

**Issue by tanjilseebiz** [AuthorizeNet/sample-code-php#62]
When I run `PaymentTransactions/charge-credit-card.php ` in browser I get the following error.
` /PaymentTransactions/charge-credit-card.php - require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /home/tj/seebiz/authorize.net/sample-code-php/PaymentTransactions/charge-credit-card.php on line 2
`

**Comment by zahiruldu** [comment]
Your file does not have proper folder identification to include the file. write  `require('../vendor/autoload.php');  `in your `charge-credit-card.php` file. Hope it will solve your problem.

**Comment by tanjilseebiz** [comment]
It worked!
Thank you @zahiruldu
