### ISSUE TITLE
No string message was returned with response:

### ISSUE THREAD

**Issue by ameer78** [AuthorizeNet/sample-code-php#63]
No string message was returned with error response:
    object(net\authorize\api\contract\v1\TransactionResponseType)[3211]
      private 'responseCode' => string '3' (length=1)
      private 'rawResponseCode' => null
      private 'authCode' => string '' (length=0)
      private 'avsResultCode' => string 'P' (length=1)
      private 'cvvResultCode' => string '' (length=0)
      private 'cavvResultCode' => string '' (length=0)
      private 'transId' => string '0' (length=1)
      private 'refTransID' => string '' (length=0)
      private 'transHash' => string '47E5203FA27E51E971221406BB284BDC' (length=32)
      private 'testRequest' => string '0' (length=1)
      private 'accountNumber' => string 'XXXX6456' (length=8)
      private 'entryMode' => null
      private 'accountType' => string '' (length=0)
      private 'splitTenderId' => null
      private 'prePaidCard' => null
      private 'messages' => 
        array (size=0)
          empty
      private 'errors' => 
        array (size=1)
          0 => 
            object(net\authorize\api\contract\v1\TransactionResponseType\ErrorsAType\ErrorAType)[3194]
              ...
      private 'splitTenderPayments' => 
        array (size=0)
          empty
      private 'userFields' => 
        array (size=0)
          empty
      private 'shipTo' => null
      private 'secureAcceptance' => null
      private 'emvResponse' => null
      private 'transHashSha2' => string '' (length=0)
  private 'profileResponse' => null
  private 'refId' (net\authorize\api\contract\v1\ANetApiResponseType) => null
  private 'messages' (net\authorize\api\contract\v1\ANetApiResponseType) => 
    object(net\authorize\api\contract\v1\MessagesType)[3175]
      private 'resultCode' => string 'Error' (length=5)
      private 'message' => 
        array (size=1)
          0 => 
            object(net\authorize\api\contract\v1\MessagesType\MessageAType)[3190]

**Comment by ashtru** [comment]
Please also provide more information like:
- The type of payment transaction request  e.g. authorize-credit-card, 
- The inputs to request (mask the sensitive information like credit card, transaction keys)
- If you are not using one of the sample codes, please share the code used by you.  Or at least how it is different from the particular sample code you have modified.

Is the issue reproducible? If yes, is it happening only for a particular credit card, bank account or customer profile?
It is also okay to share the request object from the `phplog` file, which auto-masks credit card information and transaction keys.

**Comment by ameer78** [comment]
Hello man
You can mark it as closed or fixed issue

**Comment by adavidw** [comment]
In the absence of any further questions, I'll close this issue for now. Please let us know if you need any more information or help.
