### ISSUE TITLE
update-subscription.php doesn't allow editing a subscription's amount?

### ISSUE THREAD

**Issue by globatum** [AuthorizeNet/sample-code-php#64]
It's not clear how I can adjust someone's subscription on my site with update-subscription.php.

The price a user pays on my site is dynamic and according to the number of emails they plan to send per month. Sometimes, they need to send more or downgrade their account meaning I need to adjust their monthly subscription accordingly. The update-subscription.php provides no way of modifying the amount or the billing cycle. Any help?

**Comment by ashtru** [comment]
- The `amount` for a subscription can be changed, as it is one of the request fields for [Update Subscription API](http://developer.authorize.net/api/reference/#recurring-billing-update-a-subscription). So, in the [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/update-subscription.php#L36) for update-subscription, you can add following code before sending the request:
  
    `$subscription->setAmount($amount);`
  
- In the [SDK](https://github.com/AuthorizeNet/sdk-php), you can find this info by searching for [ARBUpdateSubscriptionRequest](https://github.com/AuthorizeNet/sdk-php/blob/9d24edc675362b6349983205b8288d178fa0c469/lib/net/authorize/api/contract/v1/ARBUpdateSubscriptionRequest.php#L17), in which subscription is of type [ARBSubscriptionType](https://github.com/AuthorizeNet/sdk-php/blob/9d24edc675362b6349983205b8288d178fa0c469/lib/net/authorize/api/contract/v1/ARBSubscriptionType.php#L27) which has the amount field.
 
-  What do you mean by modifying the billing cycle? Is the date of payment changing every month (for a monthly subscription?) 
As stated in the [developer reference](http://developer.authorize.net/api/reference/#recurring-billing-update-a-subscription) , the payments for subscriptions are made automatically based on start date and the interval. The interval cannot be modified(and hence the field is not mentioned as part of paymentSchedule). After the first successful payment, start date cannot be modified.

![image](https://cloud.githubusercontent.com/assets/14973353/22211949/d39c0232-e1b4-11e6-8141-3068755c2101.png)

- As the customer needs to provide dates every time, it seems you do not automatic payments, and hence subscriptions. In that case, you can simply [create a customer profile](https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-customer-profile.php) for that customer, and [charge the customer profile](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php) based on the periodic inputs.
 Again, the sample codes only cover limited use cases of a particular API. Search/browse the SDK code to see what other fields can be set in requests or fetched from a response object. 
For detailed information, please refer the [developer reference](http://developer.authorize.net/api/reference) . You can also use the Try-It tab for each API using your sandbox credentials(or default credentials) to test out different requests.

**Comment by adavidw** [comment]
In the absence of any further questions, I'll close this issue for now. Please reopen if there's any more information or help you need.
