### ISSUE TITLE
How to Pass BillTo Address & Name to php SDK?

### ISSUE THREAD

**Issue by MilesYM** [AuthorizeNet/sample-code-php#67]
Hi guys,

Thanks for this awesome samples, really helpful.
I’m trying to pass the name on the card to the API but I’m not sure how to do. I figured out there was a BillTo field with name in the API requests parameters but I’m not able to find it in the PHP SDK.

So far my piece of code is very similar to the original example:

`
  
              // Common setup for API credentials  
		$merchantAuthentication = new AnetAPI\MerchantAuthenticationType();   
		$merchantAuthentication->setName($this->ci->config->item('AUTHNETAPILOGINID'));   
		$merchantAuthentication->setTransactionKey($this->ci->config->item('AUTHNETKEY'));   
                $refId = 'ref' . time();

		// Remove potential white spaces
		$ccn = preg_replace('/\s+/', '', $ccn);

		// Create the payment data for a credit card
		$creditCard = new AnetAPI\CreditCardType();
		$creditCard->setCardNumber( intval( $ccn ) );
		$creditCard->setExpirationDate( $exp );
      	$creditCard->setCardCode( $cvc );
		$paymentOne = new AnetAPI\PaymentType();
		$paymentOne->setCreditCard($creditCard);

		$order = new AnetAPI\OrderType();
		$order->setDescription("Ticket");

		// Create a transaction
		$transactionRequestType = new AnetAPI\TransactionRequestType();
		$transactionRequestType->setTransactionType("authCaptureTransaction");   
		$transactionRequestType->setAmount( $amount );
      	        $transactionRequestType->setOrder( $order );
		$transactionRequestType->setPayment($paymentOne);
		
		$request = new AnetAPI\CreateTransactionRequest();
		$request->setMerchantAuthentication($merchantAuthentication);
		$request->setRefId( $refId );
		$request->setTransactionRequest($transactionRequestType);
		$controller = new AnetController\CreateTransactionController($request);
		$response_api = $controller->executeWithApiResponse(\net\authorize\api\constants\ANetEnvironment::PRODUCTION);   

		if ($response_api != null)
		{
                        // More Code
                }
`

**Comment by ashtru** [comment]
@MilesYM Thanks for reaching out to us.

Similar to the other [samples](https://github.com/AuthorizeNet/sample-code-php/blob/9e9ad8b28953ce10dc2734d160f3b868b0b62ecc/CustomerProfiles/create-customer-profile.php), the code for setting billing address should look something like this:

```
	  // Create the Bill To info
	  $billto = new AnetAPI\CustomerAddressType();
	  $billto->setFirstName("Ellen");
	  $billto->setLastName("Johnson");
	  $billto->setCompany("Souveniropolis");
	  $billto->setAddress("14 Main Street");
	  $billto->setCity("Pecan Springs");
	  $billto->setState("TX");
	  $billto->setZip("44628");
	  $billto->setCountry("USA");
         //Assign to the transactionRequest field
	 $transactionRequestType->setBillTo($billto);

```


**Steps**
- [Search](https://github.com/AuthorizeNet/sdk-php/search?utf8=%E2%9C%93&q=CreateTransactionRequest) the repository to get the class definition for the request type [CreateTransactionRequest](https://github.com/AuthorizeNet/sdk-php/blob/9d24edc675362b6349983205b8288d178fa0c469/lib/net/authorize/api/contract/v1/CreateTransactionRequest.php#L12), which gives you 
- the class [TransactionRequestType](https://github.com/AuthorizeNet/sdk-php/blob/9d24edc675362b6349983205b8288d178fa0c469/lib/net/authorize/api/contract/v1/TransactionRequestType.php#L110) for `transactionRequest `field, which gives you 
- the CustomerAddressType class for the `billTo` field and the [setter](https://github.com/AuthorizeNet/sdk-php/blob/9d24edc675362b6349983205b8288d178fa0c469/lib/net/authorize/api/contract/v1/TransactionRequestType.php#L622) to be called.

**Comment by MilesYM** [comment]
Great! Thank you so much  Ashtru!

Sorry I haven’t see that in the samples! I’m going to try! 
What’s the minimum required ? Name and postal code ?

Thanks!

**Comment by MilesYM** [comment]
How do you do when there is a Middle name or a suffix in name ?

**Comment by ashtru** [comment]
In general, there are no required fields for a billing address.
Some exception are:
  - Depending on the processor some fields might be required. You can see the **Request** Tab for CreateTransaction API in [developer reference](http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card) 
![image](https://cloud.githubusercontent.com/assets/14973353/22497287/a2e4093c-e876-11e6-8336-8801cf4a46ab.png)

  - Similarly for creating a shipping address, 
![image](https://cloud.githubusercontent.com/assets/14973353/22497304/c175e4ce-e876-11e6-8187-11fc80694f67.png)

- In the Merchant Interface([sandbox](https://sandbox.authorize.net/)), in Customer Information Manager, if _Add Profile_ is selected , for shipping address, atleast one out of name and company field must be provided.

**Comment by adavidw** [comment]
We've updated the charge-credit-card and authorize-credit-card to show samples of this.
