### ISSUE TITLE
syntax error, unexpected 'use' (T_USE)

### ISSUE THREAD

**Issue by WebWars** [AuthorizeNet/sample-code-php#71]
I am using sample code from here https://developer.authorize.net/api/reference/index.html#payment-transactions-authorize-a-credit-card. I am using https://github.com/AuthorizeNet/sdk-php/releases and require 'path/to/anet_php_sdk/autoload.php'; since I am not using composer. and I get syntax error, unexpected 'use' (T_USE). on these two lines 
use net\authorize\api\contract\v1 as AnetAPI;
use net\authorize\api\controller as AnetController;

**Comment by ashtru** [comment]
Composer is required for generating the vendor folder. After which, you are free to use the custom autoloader.
One way can be to run the `composer update` in another system, and copy the vendor folder from there into your code environment.
Please respond if this can work for you.

**Comment by adavidw** [comment]
Since there hasn't been an update, I'm going to close this issue. If you have more information to provide related to this issue, feel free to reopen it.

**Comment by idextrus** [comment]
WebWars, did you resolve this? I am running into the same issue and am looking for a resolution. Thanks!

**Comment by WebWars** [comment]
> WebWars, did you resolve this? I am running into the same issue and am looking for a resolution. Thanks!

I don't even remember! I probably transfered the site locally on xamp and installed composer and then reuplaoded back on the server. I hope this helps

**Comment by idextrus** [comment]
and the you loaded the SDK via:
require 'vendor/autoload.php';?

**Comment by WebWars** [comment]
Probably yes!
