### ISSUE TITLE
Magic ANetResponseType::getTransactionResponse method?

### ISSUE THREAD

**Issue by alexsasharegan** [AuthorizeNet/sample-code-php#76]
I'm having a hard time following the sample SDK code for parsing responses. All the sample code uses this line after constructing a controller and executing a response: 
```php
<?php

$response  = $controller->executeWithApiResponse( 
  \net\authorize\api\constants\ANetEnvironment::SANDBOX
);
$tresponse = $response->getTransactionResponse();
```
The `getTransactionResponse` method does not exist in the method. I was expecting to see a `__call()` method that reflects the method name and accesses the corresponding property, or a class being extended where this method was present, but I didn't find anything.

Is there some php magic here that I'm missing? I would really love to know how this ticks. It's hard to use an SDK with methods that aren't enumerated in the code!

**Comment by kikmak42** [comment]
getTransactionResponse() is part of the Authorize.Net PHP SDK. It is defined  [here](https://github.com/AuthorizeNet/sdk-php/blob/9d24edc675362b6349983205b8288d178fa0c469/lib/net/authorize/api/contract/v1/CreateTransactionResponse.php) in the php sdk.
