### ISSUE TITLE
Older Version of SDK

### ISSUE THREAD

**Issue by upstateInc** [AuthorizeNet/sample-code-php#84]
Hello,
       The new version of SDK requires php 5.5 but our hosting has 5.4.5. It is not possible to migrate to php 5.5 just for one application. So is it possible we can use an older version of sdk ?
I got an idea that older versions can be used.
So I changed the composer.json code to 
{

  "require": {
  "php": ">=5.2.0",
  "ext-curl": "*",
  "authorizenet/authorizenet": "1.8.1",
  "jms/serializer": "xsd2php-dev as 0.18.0"
},
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/goetas/serializer.git"
    }]

}

and then from putty typed the following code
composer require authorizenet/authorizenet

but still receiving the error message

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - goetas/xsd2php 2.1.x-dev requires php >=5.5 -> your PHP version (5.4.45) does not satisfy that requirement.
    - goetas/xsd2php 2.1.0 requires php >=5.5 -> your PHP version (5.4.45) does not satisfy that requirement.
    - goetas/xsd2php 2.0.0-alpha requires goetas/xsd-reader >=1.0.1,<2.0 -> satisfiable by goetas/xsd-reader[1.0.1] but these conflict with your requirements or minimum-stability.
    - goetas/xsd2php 2.0.0 requires php >=5.5 -> your PHP version (5.4.45) does not satisfy that requirement.
    - Installation request for goetas/xsd2php 2.*@dev -> satisfiable by goetas/xsd2php[2.0.0, 2.0.0-alpha, 2.1.0, 2.1.x-dev].

Installation failed, reverting ./composer.json to its original content.

What wrong possibly I am doing kindly help...
Thanks in advance.

**Comment by adavidw** [comment]
Sorry, we can't support anything earlier than 5.5, both because our dependencies require it, and for security reasons.
