### ISSUE TITLE
Simple curl example to fetch Authorize.net transactions

### ISSUE THREAD

**Issue by upstateInc** [AuthorizeNet/sample-code-php#85]
Hello,
Can we fetch the details of individual transactions by submitting the transaction Id from API without using SDK and using simple curl only?
If yes kindly provide an example..

Thanks in advance.

**Comment by adavidw** [comment]
Hi,

The actual API reference for that request is at http://developer.authorize.net/api/reference/index.html#transaction-reporting-get-transaction-details.

There’s a sample request there in XML or JSON format, and all you’d have to do is use curl to post that whole request to the endpoint URL. (Sandbox: https://apitest.authorize.net/xml/v1/request.api or production: https://api.authorize.net/xml/v1/request.api)

**Comment by adavidw** [comment]
With curl on the command line, it would look something like this:

`curl -X POST -H "Content-Type: text/xml" -d ' <getTransactionDetailsRequest xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
    <merchantAuthentication>
        <name>5KP3u95bQpv</name>
        <transactionKey>346HZ32z3fP4hTG2</transactionKey>
    </merchantAuthentication>
      <transId>12345</transId>
</getTransactionDetailsRequest>' "https://apitest.authorize.net/xml/v1/request.api"`
