### ISSUE TITLE
get-list-of-subscriptions.php 小问题

### ISSUE THREAD

**Issue by phpstudyOne** [AuthorizeNet/sample-code-php#91]
在`RecurringBilling/get-list-of-subscriptions.php` 文件中，使用了如下代码：
``` php
    $sorting = new AnetAPI\ARBGetSubscriptionListSortingType();
    $sorting->setOrderBy("id");
    $sorting->setOrderDescending("false");
```
但是实际上 `setOrderDescending` 接受的参数应该为  `true` 或者 `false`;

看意图是不进行倒序排列，但是如果传递`"false"`参数是为 `true`的，是倒序排列的,这会带来困惑。

**Comment by adavidw** [comment]
I have [translated through Google Translate](https://translate.googleusercontent.com/translate_c?depth=1&hl=en&rurl=translate.google.com&sl=zh-CN&sp=nmt4&tl=en&u=https://github.com/AuthorizeNet/sample-code-php/issues/91&usg=ALkJrhgfJtqiK0DKerRtAbC9u4zjySTiAg), so I hope that I understand correctly.

In this code, if the `setOrderDescending` parameter is set to "false", the order will be _ascending_ by "id". If the `setOrderDescending` parameter is set to true, then the order will be _descending_ by "id".

If you don't send either `setOrderBy` or `setOrderDescending`, the default behavior would be to return the results in ascending order by "id"

**Comment by phpstudyOne** [comment]
`"false"`  typeof is string .   
`false` typeof is bool .

identify `$sorting->setOrderDescending("false");`  with `$sorting->setOrderDescending(true);` 

we  can use  
```php
$sorting->setOrderDescending(false);
```
rather than
```php
$sorting->setOrderDescending("false");
```
