### ISSUE TITLE
can't create account at developer.authorize.net

### ISSUE THREAD

**Issue by tstizzle** [AuthorizeNet/sample-code-php#92]
has anyone else tried creating an account on developer.authorize.net?   i have created 4 different accounts, on two different computer, both with and without 3rd party cookies.  it always appears to succeed, and i get sandbox login ID and key.  BUT, the credentials don't work and i can never log into the sandbox account.  

yet another obstacle to working with authorize.net.

**Comment by brianmc** [comment]
What error do you see Terence?

Brian

**Comment by tstizzle** [comment]
hi brian,
every time, every account, the same thing.  simply a login error:
The Login ID or Password entered is invalid. Please try again.

**Comment by brianmc** [comment]
Ok so just to make sure:  if you're logging into the Merchant interface (sandbox.authorize.net) you'll need the username and password you created yourself during sandbox signup.  If you're using the sandbox API (apitest.authorize.net) you'll need the credentials (api_login_id and transaction_key) that were generated after successful sandbox signup.

Brian

**Comment by tstizzle** [comment]
hi brian,

first, thanks for the response on this issue.  i (and others) do appreciate your time, especially on a sunday.

now, onto the login/account issue.  i am not trying to log into a developer account using loginid and transaction key.  conversely, i am not trying to test payments using the username and password for my developer account.

i created 4 accounts using this link: https://developer.authorize.net/hello_world/sandbox/ .  every time i successfully received a loginid and transaction key (as well as the same secret for all accounts - so that may not be such a "secret").

i try to login using this link and have not once been able to log in: https://sandbox.authorize.net/

in looking at the cookie issued after account creation, it appears that the cookie i received from developer.authorize.net is valid for sandbox.authorize.net.  yet i cannot login.

as i mentioned, this problem spans 2 different dev computers, 4 different accounts, 3rd party cookies or not, over several weeks.  

perhaps you could check error logs and see why i am unable to log into any account i have created on developer.authorize.net?

thanks again for your help on a sunday.  that's a high quality touch.

**Comment by brianmc** [comment]
No worries Terence, I know when you're trying to get something done it doesn't matter what day or time it is.  Send me one of the usernames you chose when you created the accounts and I will look at the state of the account, in case it's locked out or at least see the error attempts.

**Comment by adavidw** [comment]
I'm going to go ahead and close this as it's not directly related to this repo. Terence, if you're still having trouble, feel free to reach out to Brian or myself.
