### ISSUE TITLE
Merge Customer Profiles

### ISSUE THREAD

**Issue by it-all** [AuthorizeNet/sample-code-php#95]
Hi, is there a function or way to move a payment profile from one customer profile to another, or a way to merge customer profiles?

There are times we erroneously create multiple profiles for the same customer.

**Comment by adavidw** [comment]
Hi @it-all,

Unfortunately, there's no current way to do what you describe, but I can definitely see the usefulness in such a scenario.
 
On our [developer community forum](https://community.developer.authorize.net/), we have a special [Ideas Forum](https://community.developer.authorize.net/t5/Ideas/idb-p/ideas) where participants can take a look, contribute feedback, and vote for new features. I'd encourage you to post this onto the Ideas Forum as a suggestion for a future enhancement.
