### ISSUE TITLE
Transaction Failed Error code : 11 Error message : A duplicate transaction has been submitted.

### ISSUE THREAD

**Issue by yasha8** [AuthorizeNet/sample-code-php#96]
when trying to send authorization and capture request 

can not change my price - its always the same amount , 

what other variable can I change to avoid getting this error ?

**Comment by rhldr** [comment]
Using the response code lookup tool, you can learn more about the error and options for working around the issue.  https://developer.authorize.net/api/reference/responseCodes.html?code=11
