### ISSUE TITLE
Create Customer Profile not returning address ID

### ISSUE THREAD

**Issue by KevinBatdorf** [AuthorizeNet/sample-code-php#97]
Using code from `create-customer-profile.php` the `$response->getCustomerShippingAddressIdList()` is empty. That number is required for creating a subscription.

Further, I can't find any other request that will return this ID. 

It would appear the billing is being accepted:
![screen shot 2017-07-16 at 5 56 35 pm](https://user-images.githubusercontent.com/1478421/28246919-32420222-6a50-11e7-980a-36aeaa020b80.png)

Maybe you can show how to create a subscription without hardcoding all the IDs? Thanks!

**Comment by adavidw** [comment]
Hi @KevinBatdorf,

I just updated the ```create-customer-profile.php``` sample to show an example of adding a shipping address. Once a shipping address is added into the profile, the ```getCustomerShippingAddressIdList()``` call should work as expected.

If anything else is unclear, please reopen this and let us know.
